[package]
name = "solrate-contract-aptos"
version = "1.0.0"
authors = []

[addresses]
solrate = "_"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
